# Generated by Django 3.2.2 on 2021-07-07 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_custdomer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='custdomer',
        ),
    ]
