# Generated by Django 3.2.2 on 2021-07-07 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210708_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='username',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='user',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='seller', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
