# Generated by Django 3.2.5 on 2021-07-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_otp_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='godowns',
        ),
        migrations.AlterField(
            model_name='seller',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='seller',
            name='username',
            field=models.CharField(max_length=12),
        ),
    ]
