# Generated by Django 3.2.2 on 2021-06-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=460)),
                ('image', models.ImageField(upload_to='banner/')),
                ('url', models.CharField(max_length=460, null=True)),
            ],
        ),
    ]
