# Generated by Django 3.2.4 on 2021-06-30 18:52

from django.db import migrations, models
import home.validators


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='box_banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=460)),
                ('image', models.ImageField(upload_to='box_banner/', validators=[home.validators.clean_image])),
                ('url', models.CharField(blank=True, max_length=460, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='mini_banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=460)),
                ('image', models.ImageField(upload_to='mini_banner/', validators=[home.validators.clean_image])),
                ('url', models.CharField(blank=True, max_length=460, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banner/', validators=[home.validators.clean_image]),
        ),
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.CharField(blank=True, max_length=460, null=True),
        ),
    ]
