# Generated by Django 3.2.5 on 2021-07-16 17:10

from django.db import migrations, models
import home.validators


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210701_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banner/', validators=[home.validators.clean_image]),
        ),
    ]
